// Natural Earth 1:50m -> a clipped, simplified Python module.
// Run: node extract_basemap.mjs <countries-50m.json> <out.py>
// Source: https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-50m.json
// Natural Earth is public domain.
import fs from 'node:fs';

const [, , IN, OUT] = process.argv;
const topo = JSON.parse(fs.readFileSync(IN, 'utf8'));
const [sx, sy] = topo.transform.scale, [tx, ty] = topo.transform.translate;
const arcs = topo.arcs.map(a => { let x = 0, y = 0; return a.map(([dx, dy]) => { x += dx; y += dy; return [x * sx + tx, y * sy + ty]; }); });

// The clip has to contain the frame the map actually draws, which is not the
// bounding box of the sites. `Frame.fit` grows the short axis to the canvas
// aspect, so the fourteen PoPs spanning lon -3.7..21.0 are drawn inside a frame
// running lon -9.4..26.7. An earlier clip stopped at 25.5 and put a straight
// vertical cut through Ukraine and the Baltic about 41 px inside the panel,
// with sea drawn where land is. These bounds clear that frame on every side.
// tests/unit/test_basemap.py asserts the containment so it cannot drift back.
const LON0 = -13.0, LON1 = 30.0, LAT0 = 34.0, LAT1 = 63.0, TOL = 0.02, MIN_AREA = 0.006;
const RELEASE = '2.0.2';

const ringOf = idxs => { const p = []; for (const i of idxs) { const a = i < 0 ? arcs[~i].slice().reverse() : arcs[i]; for (let k = p.length ? 1 : 0; k < a.length; k++) p.push(a[k]); } return p; };
const polysOf = g => g.type === 'Polygon' ? [g.arcs] : g.type === 'MultiPolygon' ? g.arcs : [];
const hit = p => p.some(([x, y]) => x >= LON0 - 2 && x <= LON1 + 2 && y >= LAT0 - 2 && y <= LAT1 + 2);

function clipRing(pts) {
  const E = [[p => p[0] >= LON0, (a, b) => [LON0, a[1] + (b[1] - a[1]) * (LON0 - a[0]) / (b[0] - a[0])]],
             [p => p[0] <= LON1, (a, b) => [LON1, a[1] + (b[1] - a[1]) * (LON1 - a[0]) / (b[0] - a[0])]],
             [p => p[1] >= LAT0, (a, b) => [a[0] + (b[0] - a[0]) * (LAT0 - a[1]) / (b[1] - a[1]), LAT0]],
             [p => p[1] <= LAT1, (a, b) => [a[0] + (b[0] - a[0]) * (LAT1 - a[1]) / (b[1] - a[1]), LAT1]]];
  let out = pts;
  for (const [ins, isect] of E) {
    const inp = out; out = [];
    for (let i = 0; i < inp.length; i++) {
      const c = inp[i], p = inp[(i + inp.length - 1) % inp.length];
      const ci = ins(c), pi = ins(p);
      if (ci) { if (!pi) out.push(isect(p, c)); out.push(c); } else if (pi) out.push(isect(p, c));
    }
    if (!out.length) return null;
  }
  return out;
}
function dpLine(pts, tol) {
  const n = pts.length; if (n < 3) return pts.slice();
  const keep = new Uint8Array(n); keep[0] = keep[n - 1] = 1; const st = [[0, n - 1]];
  while (st.length) {
    const [i0, i1] = st.pop(); if (i1 <= i0 + 1) continue;
    const [ax, ay] = pts[i0], [bx, by] = pts[i1];
    const dx = bx - ax, dy = by - ay, den = Math.hypot(dx, dy) || 1e-12;
    let md = -1, mi = -1;
    for (let i = i0 + 1; i < i1; i++) { const d = Math.abs((pts[i][0] - ax) * dy - (pts[i][1] - ay) * dx) / den; if (d > md) { md = d; mi = i; } }
    if (md > tol) { keep[mi] = 1; st.push([i0, mi], [mi, i1]); }
  }
  return pts.filter((_, i) => keep[i]);
}
// A closed ring has no endpoints for Douglas-Peucker to anchor on: first equals
// last, the baseline is zero length, every perpendicular distance computes as
// zero and the whole ring collapses to two points. Split it first.
function dpRing(ring, tol) {
  const pts = ring.slice();
  const [fx, fy] = pts[0], [lx, ly] = pts[pts.length - 1];
  if (Math.abs(fx - lx) < 1e-12 && Math.abs(fy - ly) < 1e-12) pts.pop();
  if (pts.length < 4) return null;
  let far = 0, fd = -1;
  for (let i = 1; i < pts.length; i++) { const d = Math.hypot(pts[i][0] - pts[0][0], pts[i][1] - pts[0][1]); if (d > fd) { fd = d; far = i; } }
  return dpLine(pts.slice(0, far + 1), tol).slice(0, -1)
    .concat(dpLine(pts.slice(far).concat([pts[0]]), tol).slice(0, -1));
}
const area = r => Math.abs(r.reduce((s, p, i) => { const q = r[(i + 1) % r.length]; return s + (p[0] * q[1] - q[0] * p[1]); }, 0) / 2);

const out = [];
for (const g of topo.objects.countries.geometries) {
  const rings = [];
  for (const poly of polysOf(g)) for (const ring of poly) {
    const r = ringOf(ring); if (!hit(r)) continue;
    const c = clipRing(r); if (!c || c.length < 4) continue;
    const s = dpRing(c, TOL); if (!s || s.length < 4 || area(s) < MIN_AREA) continue;
    rings.push(s);
  }
  if (rings.length) out.push([g.properties.name, rings]);
}
out.sort((a, b) => a[0].localeCompare(b[0]));

const r3 = v => Math.round(v * 1000) / 1000;
const nCountries = out.length;
const nRings = out.reduce((s, [, r]) => s + r.length, 0);
const nPoints = out.reduce((s, [, rs]) => s + rs.reduce((t, r) => t + r.length, 0), 0);
const body =
`"""Europe coastlines and borders. GENERATED by scripts/extract_basemap.mjs.

Source: Natural Earth 1:50m, taken from world-atlas ${RELEASE} countries-50m.json.
Licence: public domain.
Clipped to lon ${LON0}..${LON1} and lat ${LAT0}..${LAT1}, simplified to ${TOL} degrees.
Holds ${nCountries} countries, ${nRings} rings, ${nPoints} points.

Embedded so the map needs no network access at render time. Do not hand-edit.
Rerun the script to change it; tests/unit/test_basemap.py reads the counts above
and fails when they drift from the data below.
"""

FRAME = (${LON0}, ${LON1}, ${LAT0}, ${LAT1})

# name -> list of rings, each a list of (lon, lat)
COUNTRIES: dict[str, list[list[tuple[float, float]]]] = {
${out.map(([n, rings]) => `    ${JSON.stringify(n)}: [\n${rings.map(r => `        [${r.map(([x, y]) => `(${r3(x)},${r3(y)})`).join(',')}],`).join('\n')}\n    ],`).join('\n')}
}
`;
fs.writeFileSync(OUT, body);
console.log(`${nCountries} countries, ${nRings} rings, ${nPoints} points, ${Math.round(body.length / 1024)} KB`);
