"""`basemap.py`, against the two ways a regenerated basemap goes wrong quietly.

The module is generated by `scripts/extract_basemap.mjs` and never hand-edited,
so nothing here tests logic. It tests that the artifact in the tree still says
what its own header says it says.

A collapsed ring. Douglas-Peucker has no endpoint to anchor on when first equals
last: the baseline has zero length, every perpendicular distance computes as
zero, and the ring drops to two points. The script splits rings before
simplifying, and the symptom when it stops doing that is subtle, because rings
clipped open by the frame edge survive. The map keeps Norway and Ukraine and
loses France. The point count and the per-ring shape assertions below are what
catch that without anyone having to look at a picture.

An inflated artifact. Rerunning the script at a finer tolerance costs nothing at
the prompt and adds tens of thousands of coordinates that every worker process
then parses at import. The size bound turns that into a failing test rather than
a slow pipeline nobody traces back to a basemap.
"""

import ast
import math
import re
from pathlib import Path

from infrahub_demo_otn import basemap
from infrahub_demo_otn.units import microdeg_to_deg
from tests.unit.conftest import objects_of_kind

RINGS = [ring for rings in basemap.COUNTRIES.values() for ring in rings]


def _pop_coordinates() -> list[tuple[float, float]]:
    """The shipped PoPs as (lon, lat) degrees, read from `objects/`.

    The customer campus is excluded because the map does not draw it and so
    does not frame around it.
    """
    return [
        (microdeg_to_deg(int(site["longitude_microdeg"])), microdeg_to_deg(int(site["latitude_microdeg"])))
        for site in objects_of_kind("OtnSite")
        if site.get("site_type", "pop") == "pop"
    ]


MAX_BYTES = 100 * 1024
"""Generated at 0.02 degrees the module is about 89 KB. Halving the tolerance
roughly doubles it, so this bound is loose enough to survive a country being
added upstream and tight enough to reject a finer simplification."""

MIN_RING_POINTS = 4
"""Three corners and the implicit closing edge. A collapsed ring has two."""

MIN_RING_AREA_SQ_DEG = 0.006
"""`MIN_AREA` in the extraction script. Smaller rings are dropped there."""


def header() -> str:
    assert basemap.__doc__ is not None
    return basemap.__doc__


def claimed(pattern: str) -> tuple[float, ...]:
    """The numbers the module docstring claims, as floats in the order written."""
    match = re.search(pattern, header())
    assert match is not None, f"the header no longer states {pattern!r}"
    return tuple(float(group) for group in match.groups())


def shoelace_area(ring: list[tuple[float, float]]) -> float:
    """Twice the signed area, halved and made positive. The closing edge is implicit."""
    total = 0.0
    for index, (x0, y0) in enumerate(ring):
        x1, y1 = ring[(index + 1) % len(ring)]
        total += x0 * y1 - x1 * y0
    return abs(total) / 2


# ---------------------------------------------------------------------------
# The rings
# ---------------------------------------------------------------------------


def test_there_is_something_to_draw() -> None:
    assert basemap.COUNTRIES
    assert all(rings for rings in basemap.COUNTRIES.values())
    assert all(isinstance(name, str) and name for name in basemap.COUNTRIES)


def test_every_ring_closes() -> None:
    """Closed implicitly, by the renderer, not by a repeated final point.

    Both halves matter. A repeated point would draw a zero-length segment and
    double-count in the point total, and a ring of two points is the
    Douglas-Peucker collapse this file exists to catch.
    """
    for ring in RINGS:
        assert len(ring) >= MIN_RING_POINTS
        assert ring[0] != ring[-1]
        assert shoelace_area(ring) >= MIN_RING_AREA_SQ_DEG


def test_every_point_is_a_pair_of_finite_numbers() -> None:
    """The annotation says float and a few literals are written as int.

    `(20,39.71)` is what rounding to three decimals produces for a whole degree,
    and Python reads that first value as an int. Arithmetic does not care and
    neither does the renderer, so the check is numeric and finite, not float.
    """
    for ring in RINGS:
        for point in ring:
            assert isinstance(point, tuple)
            assert len(point) == 2
            lon, lat = point
            assert isinstance(lon, (int, float)) and math.isfinite(lon)
            assert isinstance(lat, (int, float)) and math.isfinite(lat)


def test_every_point_lies_inside_the_declared_frame() -> None:
    """FR-013. The data is clipped, so nothing may sit outside the frame it names.

    A point beyond the frame is a point the renderer draws over the panel or off
    the canvas, and rounding the clipped coordinates to three decimals is the way
    it would happen.
    """
    lon0, lon1, lat0, lat1 = basemap.FRAME
    for ring in RINGS:
        for lon, lat in ring:
            assert lon0 <= lon <= lon1
            assert lat0 <= lat <= lat1


def test_the_frame_is_wider_than_it_is_tall_and_covers_western_europe() -> None:
    """Transposing the frame tuple is the cheap mistake, and it still parses."""
    lon0, lon1, lat0, lat1 = basemap.FRAME
    assert lon0 < lon1
    assert lat0 < lat1
    # Madrid and Warsaw are the east and west extremes of the fourteen PoPs, and
    # Madrid and Copenhagen the north and south. The clip clears all four.
    assert lon0 <= -3.71 and lon1 >= 21.02
    assert lat0 <= 40.41 and lat1 >= 55.68


def test_the_clip_contains_the_frame_the_map_actually_draws() -> None:
    """The bug this exists for: coastlines that stop inside the drawing area.

    The drawn frame is not the bounding box of the sites. `Frame.fit` grows the
    short axis to the canvas aspect, so the fourteen PoPs spanning lon
    -3.7 to 21.0 are drawn inside a frame reaching lon 26.7. A clip that stops
    at 25.5 satisfies every other test in this file and still puts a straight
    vertical cut through Ukraine and the Baltic, with sea drawn where land is.

    Asserted against the real site coordinates and the real canvas, because the
    two numbers that have to agree live in different files and nothing else
    compares them.
    """
    from infrahub_demo_otn import mapchrome
    from infrahub_demo_otn.cartography import Frame

    sites = _pop_coordinates()
    assert len(sites) == 14, "the fixture stopped reading the shipped PoPs"

    # The canvas belongs to `mapchrome.py`, which is the module both maps fit
    # their frame with. Reading it off either renderer would pass on a copy.
    frame = Frame.fit(
        sites,
        width=mapchrome.CANVAS_WIDTH,
        height=mapchrome.CANVAS_HEIGHT,
        pad_left=mapchrome.PAD_LEFT,
        pad_right=mapchrome.PAD_RIGHT,
        pad_top=mapchrome.PAD_TOP,
        pad_bottom=mapchrome.PAD_BOTTOM,
    )
    lon_min = math.degrees(frame.xmin)
    lon_max = math.degrees(frame.xmax)
    lat_min = math.degrees(2 * math.atan(math.exp(frame.ymin)) - math.pi / 2)
    lat_max = math.degrees(2 * math.atan(math.exp(frame.ymax)) - math.pi / 2)

    lon0, lon1, lat0, lat1 = basemap.FRAME
    assert lon0 <= lon_min, f"the map draws west to {lon_min:.2f} and the coastlines stop at {lon0}"
    assert lon1 >= lon_max, f"the map draws east to {lon_max:.2f} and the coastlines stop at {lon1}"
    assert lat0 <= lat_min, f"the map draws south to {lat_min:.2f} and the coastlines stop at {lat0}"
    assert lat1 >= lat_max, f"the map draws north to {lat_max:.2f} and the coastlines stop at {lat1}"


# ---------------------------------------------------------------------------
# The header against the data
# ---------------------------------------------------------------------------


def test_the_header_names_its_source_and_its_licence() -> None:
    """FR-013. The data is redistributed, so the release and the licence ship with it."""
    text = header()
    assert "GENERATED by scripts/extract_basemap.mjs" in text
    assert "Natural Earth 1:50m" in text
    assert "world-atlas 2.0.2" in text
    assert "public domain" in text


def test_the_counts_in_the_header_match_the_data() -> None:
    """A regeneration that moves one without the other fails here.

    The header is the only human-readable record of what the script produced, so
    a stale count is a lie about the artifact and about which tolerance made it.
    """
    countries, rings, points = claimed(r"Holds (\d+) countries, (\d+) rings, (\d+) points")
    assert len(basemap.COUNTRIES) == countries
    assert len(RINGS) == rings
    assert sum(len(ring) for ring in RINGS) == points


def test_the_clip_frame_in_the_header_matches_the_frame_constant() -> None:
    numbers = claimed(r"Clipped to lon (-?[\d.]+)\.\.(-?[\d.]+) and lat (-?[\d.]+)\.\.(-?[\d.]+)")
    assert numbers == tuple(float(value) for value in basemap.FRAME)


def test_the_header_states_the_tolerance_the_data_was_simplified_at() -> None:
    (tolerance,) = claimed(r"simplified to ([\d.]+) degrees")
    assert tolerance == 0.02


# ---------------------------------------------------------------------------
# The size of the artifact
# ---------------------------------------------------------------------------


def test_the_module_stays_small_enough_to_import_cheaply() -> None:
    """E4. Every worker process parses these literals once.

    A finer tolerance is a one-word edit to the script and shows up nowhere else,
    so the bound is the thing that reports it.
    """
    size = Path(basemap.__file__).stat().st_size
    assert size <= MAX_BYTES, f"basemap.py is {size / 1024:.1f} KB, over the {MAX_BYTES / 1024:.0f} KB bound"


def test_the_module_imports_nothing_at_all() -> None:
    """Pure data. Nothing under `src/` may reach for the SDK, and this file needs no one."""
    tree = ast.parse(Path(basemap.__file__).read_text(encoding="utf-8"))
    assert not [node for node in ast.walk(tree) if isinstance(node, (ast.Import, ast.ImportFrom))]
